### ISSUE TITLE
Add the include files fo the repo (basic-init.ly and snare-init.ly)

### ISSUE THREAD

**Issue by djbclark** [zeta12ti/transcriptions#3]
Would love to look at this stuff as an example, but can't find basic-init.ly anywhere. I did find snare--init.ly and graphics.ly up in pastebin, but guessing there might be newer versions now, and it'd also make sense to add them to the repo here.

**Comment by zeta12ti** [comment]
`snare-init.ly` and `graphics.ly` are in [`/include`](https://github.com/zeta12ti/transcriptions/tree/master/include). I'm not sure what `basic-init.ly` is, but `basic-setup.ly` is also in [`/include`](https://github.com/zeta12ti/transcriptions/tree/master/include). Is there some file that references `basic-init.ly`?

**Comment by djbclark** [comment]
Sorry, I'm blind, and apparently Google doesn't index file names on github. basic-init.ly was referenced from the older version of snare-init.ly but isn't in the newer. So feel free to close as PEBKAC :) And thanks for making this available!

**Comment by zeta12ti** [comment]
No problem. I'm just glad someone's getting use out of this!
